### ISSUE TITLE
Incompatibility with latest gradle-docker-plugin

### ISSUE THREAD

**Issue by mfulgo** [nebula-plugins/nebula-docker-plugin#15]
[NebulaDockerPlugin](https://github.com/nebula-plugins/nebula-docker-plugin/blob/v1.2.3/src/main/groovy/nebula/plugin/docker/NebulaDockerPlugin.groovy#L78) makes the assumption that the application tar is copied to `$build/docker`. However, the latest versions of the `gradle-docker-plugin` sync those files into `$build/docker/app-lib`.

See https://github.com/bmuschko/gradle-docker-plugin/issues/618

**Comment by liviutudor** [comment]
Good find! I will spin an update of this later today.

**Comment by liviutudor** [comment]
see https://github.com/nebula-plugins/nebula-docker-plugin/pull/18/ which should fix it.

**Comment by liviutudor** [comment]
This is still an issue with `v1.4.0` so I'm reopening this.

**Comment by liviutudor** [comment]
Fixed in `v1.4.1`
