### ISSUE TITLE
Tagging the latest image dependsOn pushing

### ISSUE THREAD

**Issue by mfulgo** [nebula-plugins/nebula-docker-plugin#17]
The `dockerTagImage${envir}Latest` task declares a dependency on `pushImage${envir}`. However, I think both tagging tasks should just depend on `buildImage`. See [NebulaDockerPlugin#L38](https://github.com/nebula-plugins/nebula-docker-plugin/blob/master/src/main/groovy/nebula/plugin/docker/NebulaDockerPlugin.groovy#L38)

I ran into this when trying to use a custom task to push up the docker images: My push task depends on `dockerTagImage${envir}Latest`.  Since `pushImage${envir}` fails (for AWS ECR authentication reasons), my task doesn't get to run.

If `dockerTagImage${envir}Latest` relied on `buildImage` (or `dockerTagImage${envir}`) instead, I believe there would be no issue.

**Comment by liviutudor** [comment]
Tagging the image only makes sense if you push the image to the repository. And to get the image there you need to push it first so to me the dependency chain makes sense.

What is the use case for having a locally tagged image but not remote?

**Comment by liviutudor** [comment]
Leaving this as `invalid` and will close at a later stage if no update on this is received.

**Comment by mfulgo** [comment]
> "Tagging the image only makes sense if you push the image to the repository."
Do you mean tagging the image *with `latest`*?

I still want to push the image to a remote registry, I just need to do it using my own custom task, and I'd like for my task to have both the specific and `latest` tags available to push. I can put the creation of the `latest` tag in my own task, I was just hoping to leverage the one that's automatically created by this plugin.

**Comment by liviutudor** [comment]
So you want this plugin to only tag an image locally -- and then later on you would push this via other means (script/manually/etc) including the tag?

**Comment by mfulgo** [comment]
Correct. That's what I'm doing with the `dockerTagImage${envir}` task right now, and I'd like to be able to do the same for `latest`.

**Comment by liviutudor** [comment]
I see. I never envisaged this as a usage scenario -- not saying it's not valid, just never thought of it.
Any reason why the pushing of the image cannot be done via this plugin?
I prefer having a chain of dependencies which trigger everything -- such that specifying `pushLatestImage` would also take care of tagging but the case you are describing is valid -- albeit outside the needs this plugin was set to serve initially.
I am thinking of having this as a configuration option -- would that work for you? Something like this:

```groovy
nebulaDocker {
   //...
   tagWithoutPush = true  //default to false but setting it to true would have the effect you described
  //...
}
```

**Comment by mfulgo** [comment]
Yes, I think that would work just fine for me. Thanks! 

A possible alternative, couldn't `pushLatestImage` depend on both `pushImage` and `dockerTagImageLatest`?

The reason pushing from the plugin doesn't work for me right now is due to some infrastructure and authentication schemes that use an external script. I'm hoping to address that in the future, but it will probably be a while.
