### ISSUE TITLE
Explain Deprecation in README

### ISSUE THREAD

**Issue by mfulgo** [nebula-plugins/nebula-docker-plugin#34]
Perhaps @chali can answer this one.

I was trying to find out why this plugin is deprecated (and in favor of what), but there isn't any comment in the README or the commit message that marks the project as deprecated. It would be helpful, for folks new to this project and existing users, if that info was included in the README.

**Comment by chali** [comment]
Hey @mfulgo, let me add a few points that contributed to deprecation to this plugin.
- We have new tooling which helps around docker experience at Netflix. It is not open source (yet) but you can learn about it [here](https://www.infoq.com/presentations/netflix-polyglot-containers/) and [here](https://www.youtube.com/watch?v=rkVdDD7gOd0)
- The plugin had a very small Netflix internal user base. Basically one team out of thousands of engineers. The Build Team, which manages Nebula plugins, is only 3 people so we have to pick projects which give us the highest value. Unfortunately, this plugin wasn't giving us that much value anymore.
- The biggest part of this plugin is convenience configuration which applies only for an internal project anyway. It means that the open-source community wasn't getting much benefit too.

Those are the biggest contributing factors why we are not maintaining the plugin anymore.

My suggestions on how to move forward for current users:
- Use directly https://github.com/bmuschko/gradle-docker-plugin. As I mentioned in previous points there are not many features in the nebula-docker plugin. Nebula-docker-plugin is built on top of the gradle-docker-plugin so switch to it shouldn't be difficult.
